name: Codeowner Reviews

on:
  pull_request:
    branches:
      - main
    types:
      - ready_for_review
      - synchronize

jobs:
  reviewers:
    name: Assign Reviewers
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v2
      
      # Recognizes and assigns reviewers and codeowners
      - uses: zattoo/reviewers@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          source: '.github/CODEOWNERS'
