  name: Reviewers

  on:
      pull_request_target

  jobs:
      reviewers:
          name: Reviewers
          runs-on: ubuntu-latest
          steps:
              - uses: actions/checkout@v2
              - uses: zattoo/reviewers@v2
                with:
                    token: ${{secrets.TOKEN}}
                    source: '.github/CODEOWNERS'
                    labels: |
                        {
                          "reviewers:projects": "**/projects/*",
                          "reviewers:platform": "/"
                        }
