name: Update Submodules

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # We do it every 6 hours.
  schedule:
    - cron:  '0 */6 * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with: 
          repository: tgstation/map_depot
          token: ${{ secrets.WRITE_SECRET }}

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Commit
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - Update Submodules"
          git add --all
          git commit -m "Submodule Update" || echo "No Changes To Commit"
          git push
